version: '3'
services:
    wordpress:
        build: ../wordpress
        links: 
            - mariadb:mysql
        environment:
            - WORDPRESS_DB_PASSWORD=password
        ports:
            - "80:80"
    mariadb:
        image: mariadb
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wp_database