apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: volume-claim4
spec:
    storageClassName: manual
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
---