apiVersion: 1

datasources:
  - name: telegraf
    type: influxdb
    access: proxy
    database: telegraf
    user: root
    password: password
    isdefault: true
    #editable: true

    #mettre CLUSTERIP:8086
    #url: http://10.103.217.12:8086
    url: http://172.17.0.11:8086
    #jsonData:
      #httpMode: GET