apiVersion: 1

datasources:
  - name: telegraf
    type: influxdb
    access: proxy
    database: telegraf
    user: root
    password: password
    isdefault: true
    #editable: true

    url: http://${INFLUXDB_SERVICE_HOST}:8086
    jsonData:
      httpMode: GET